Fix set CollectorExt.m_app error
Assigning m_app is apparently not required anymore in last RevitLookup versions and not even possible.

Error:
"""python
Traceback (most recent call last):
  File "<string>", line 83, in <module>
  File "<string>", line 63, in __init__
TypeError: can't set attributes of built-in/extension type 'CollectorExt'
"""